### ISSUE TITLE
Slackデプロイで"no implicit conversion of nil into String"エラーが起こる場合がある

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#106]
```
2019-10-27T06:36:25.571Z 6 TID-grmkapaym Github::DeployWorker JID-081a12da6237fa3027c6047c INFO: start
2019-10-27T06:36:25.617Z 6 TID-grmkapaym Github::DeployWorker JID-081a12da6237fa3027c6047c INFO: Started Github::DeployDeployTargetWorker
2019-10-27T06:36:25.631Z 6 TID-grmkapaym Github::DeployWorker JID-081a12da6237fa3027c6047c INFO: fail: 0.06 sec
2019-10-27T06:36:25.631Z 6 TID-grmkapaym WARN: {"context":"Job raised exception","job":{"class":"Github::DeployWorker","args":["job_1572158185"],"retry":false,"queue":"github_deploy","jid":"081a12da6237fa3027c6047c","created_at":1572158185.5675747,"enqueued_at":1572158185.5682974},"jobstr":"{\"class\":\"Github::DeployWorker\",\"args\":[\"job_1572158185\"],\"retry\":false,\"queue\":\"github_deploy\",\"jid\":\"081a12da6237fa3027c6047c\",\"created_at\":1572158185.5675747,\"enqueued_at\":1572158185.5682974}"}
2019-10-27T06:36:25.631Z 6 TID-grmkapaym WARN: TypeError: no implicit conversion of nil into String
2019-10-27T06:36:25.631Z 6 TID-grmkapaym WARN: /usr/local/lib/ruby/2.6.0/pathname.rb:410:in `initialize'
/usr/local/lib/ruby/2.6.0/pathname.rb:410:in `new'
/usr/local/lib/ruby/2.6.0/pathname.rb:410:in `join'
/app/lib/genova/code_manager/git.rb:30:in `initialize'
/app/app/workers/github/deploy_worker.rb:43:in `new'
/app/app/workers/github/deploy_worker.rb:43:in `deploy_target'
/app/app/workers/github/deploy_worker.rb:12:in `perform'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166:in `block in process'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108:in `local'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43:in `block in call'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/reloader.rb:73:in `block in wrap'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/reloader.rb:72:in `wrap'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42:in `call'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243:in `stats'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/job_logger.rb:8:in `call'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:73:in `global'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:125:in `block in dispatch'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:48:in `with_context'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124:in `dispatch'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165:in `process'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83:in `process_one'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71:in `run'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by naomichi-y** [comment]
genovaの問題ではなくネットワーク構成の問題だったのでクローズ。
