### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#196]
GitHubオートデプロイで稀に起きる。

```
/app/app/api/v2/helper/github_helper.rb:28:in `parse'
/app/app/api/v2/github_routes.rb:14:in `block (2 levels) in <class:GithubRoutes>'
/usr/local/bundle/gems/grape-1.5.1/lib/grape/endpoint.rb:59:in `call'
/usr/local/bundle/gems/grape-1.5.1/lib/grape/endpoint.rb:59:in `block (2 levels) in generate_api_method'
/usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:182:in `instrument'
/usr/local/bundle/gems/grape-1.5.1/lib/grape/endpoint.rb:58:in `block in generate_api_method'
/us...
```

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/releases/tag/v3.0.4
