### ISSUE TITLE
CLIデプロイ時にuninitialized constant Thor::Sandbox::GenovaCli::Deploy::Exceptions

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#219]
```
[developer@ip-172-30-68-140 genova]$ docker-compose run --rm rails thor genova:deploy service ...
Starting genova_mongo_1_1953e6820a92 ... done
Starting genova_redis_1_2a6328eb1783 ... done
Traceback (most recent call last):
	19: from /usr/local/bundle/bin/thor:23:in `<main>'
	18: from /usr/local/bundle/bin/thor:23:in `load'
	17: from /usr/local/bundle/gems/thor-1.1.0/bin/thor:6:in `<top (required)>'
	16: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	15: from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	14: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	13: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:135:in `run'
	12: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:29:in `run'
	11: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/runner.rb:43:in `method_missing'
	10: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	 9: from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	 8: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	 7: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	 6: from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
	 5: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
	 4: from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	 3: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	 2: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	 1: from /app/lib/tasks/genova.thor:78:in `service'
/app/lib/tasks/genova.thor:45:in `deploy': uninitialized constant Thor::Sandbox::GenovaCli::Deploy::Exceptions (NameError)
```

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/commit/74be81834985ae6abcf7ca5b644867e4ed9c0b51
