### ISSUE TITLE
スケジュールタスクデプロイ時にundefined method `each' for nil:NilClassエラーが出る

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#22]
`containers`が指定されていないのが原因。
例外が出るのはおかしいのでメッセージを修正する。

```
E, [2019-03-07T07:58:42.057209 #1] ERROR -- : undefined method `each' for nil:NilClass
E, [2019-03-07T07:58:42.058747 #1] ERROR -- : /data/rails/lib/genova/docker/client.rb:13:in `build_images'
/data/rails/lib/genova/ecs/client.rb:65:in `deploy'
/data/rails/lib/genova/ecs/client.rb:94:in `block (2 levels) in deploy_scheduled_tasks'
/data/rails/lib/genova/ecs/client.rb:90:in `each'
/data/rails/lib/genova/ecs/client.rb:90:in `block in deploy_scheduled_tasks'
/data/rails/lib/genova/ecs/client.rb:82:in `each'
/data/rails/lib/genova/ecs/client.rb:82:in `deploy_scheduled_tasks'
/data/rails/lib/genova/ecs/client.rb:58:in `deploy_scheduled_task'
/data/rails/lib/genova/client.rb:41:in `run'
/data/rails/lib/tasks/genova.thor:47:in `deploy'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/data/rails/lib/tasks/genova.thor:5:in `invoke_command'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/runner.rb:44:in `method_missing'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:29:in `run'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:126:in `run'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/usr/local/bundle/ruby/2.5.0/gems/thor-0.19.4/bin/thor:6:in `<top (required)>'
/usr/local/bundle/bin/thor:29:in `load'
/usr/local/bundle/bin/thor:29:in `<main>'
E, [2019-03-07T07:58:42.059891 #1] ERROR -- : Interrupt was error. {"deploy id": 20190307-075838}
I, [2019-03-07T07:58:42.063035 #1]  INFO -- : Deployment has been canceled.
```

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/pull/33
