### ISSUE TITLE
SLACK_CLIENT_IDが未定義の場合にエラーが表示され続ける

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#27]
```
genova-slack | bundler: failed to load command: rackup (/usr/local/bundle/ruby/2.5.0/bin/rackup)
genova-slack | KeyError: key not found: "SLACK_CLIENT_ID"
genova-slack |   /data/rails/bin/slack_bot_server.ru:4:in `fetch'
genova-slack |   /data/rails/bin/slack_bot_server.ru:4:in `block in <main>'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
genova-slack |   /data/rails/bin/slack_bot_server.ru:in `new'
genova-slack |   /data/rails/bin/slack_bot_server.ru:in `<main>'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:283:in `start'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
genova-slack |   /usr/local/bundle/ruby/2.5.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
genova-slack |   /usr/local/bundle/ruby/2.5.0/bin/rackup:23:in `load'
genova-slack |   /usr/local/bundle/ruby/2.5.0/bin/rackup:23:in `<top (required)>'
genova-slack exited with code 1
```

**Comment by naomichi-y** [comment]
`SLACK_CLIENT_ID` がコメントアウトされた場合に起きる。通常は発生しえないので問題ない。
