### ISSUE TITLE
"undefined method `[]' for nil:NilClass" Error

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#282]
When using GitHub's Webhook push, the following error may occur at the timing of push.

```
/app/app/api/v2/helper/github_helper.rb:19:in `parse_webhook_data'
/app/app/api/v2/github_routes.rb:16:in `block (2 levels) in <class:GithubRoutes>'
/usr/local/bundle/gems/grape-1.5.1/lib/grape/endpoint.rb:59:in `call'
/usr/local/bundle/gems/grape-1.5.1/lib/grape/endpoint.rb:59:in `block (2 levels) in generate_api_method'
/usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:205:in `instrument'
/usr/local/bundle/gems/grape-1.5.1/lib/grape/endpoint.rb:58:in `block in generate_ap...
```

**Comment by naomichi-y** [comment]
dupp
https://github.com/metaps/genova/issues/272
