### ISSUE TITLE
"undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#31]
Slackからデプロイする際、前回のビルドイメージのタグに `build` が含まれていないと以下のエラーが発生。

```
["/data/rails/lib/genova/slack/bot.rb:491:in `block in git_deployed_commit_id'", "/data/rails/lib/genova/slack/bot.rb:489:in `each'", "/data/rails/lib/genova/slack/bot.rb:489:in `git_deployed_commit_id'", "/data/rails/lib/genova/slack/bot.rb:213:in `post_confirm_deploy'", "/data/rails/app/workers/slack/deploy_confirm_worker.rb:11:in `perform'", "/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'", "/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block...
```

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/issues
