### ISSUE TITLE
GitHub deployを有効化したとき、"undefined method `[]' for nil:NilClass"エラーが出るケース

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#39]
Slackに通知された。
```
Exception occurred.
Name
NoMethodError
Message
undefined method `[]' for nil:NilClass
Backtrace
```["/data/rails/app/workers/github/deploy_worker.rb:50:in `deploy_target'", "/data/rails/app/workers/github/deploy_worker.rb:12:in `perform'", "/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'", "/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'", "/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'", "/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invok...```
Deploy Job ID
08b6022d459d93147b3385e9
```

**Comment by naomichi-y** [comment]
config/deploy.ymlにauto_deployが未定義のブランチがpushされると起きる?
