### ISSUE TITLE
Branch name may not be displayed when deploying from Slack

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#390]
genova 4.4.0以降でSlackからデプロイ時に更新済みのブランチが表示されないことがある。
`fech_config` 内で`update` が実行されなくなったことが原因。

https://github.com/metaps/genova/commit/657554947ce98d21952c6389329765fdea028e85#diff-dde8b1d654c96ff0936b0da87c08dd489f23c7ad9e2399ca6f85d82a9a55dbfaL126

**Comment by naomichi-y** [comment]
リポジトリがクローンされてない状態でデプロイを実行する際もエラーが発生する。

```
$ docker-compose run --rm rails thor genova:deploy service -r xxx -c xxx -s xxx -b develop -f
[+] Running 3/0
 ✔ Container genova-mongo-1  Running                                                                                                                                                               0.0s
 ✔ Container genova-redis-1  Running                                                                                                                                                               0.0s
 ✔ Container genova-base-1   Created                                                                                                                                                               0.0s
[+] Running 1/1
 ✔ Container genova-base-1  Started                                                                                                                                                                0.3s
I, [2024-01-06T11:34:00.019717 #1]  INFO -- : genova v4.4.1
I, [2024-01-06T11:34:00.054759 #1]  INFO -- : Begin transaction.
I, [2024-01-06T11:34:00.075415 #1]  INFO -- : Start deployment.
E, [2024-01-06T11:34:04.196838 #1] ERROR -- : Deployment failed.
E, [2024-01-06T11:34:04.203131 #1] ERROR -- : No such file or directory @ rb_sysopen - /app/tmp/repos/metaps/xxx/log_forwarder/config/deploy.yml
E, [2024-01-06T11:34:04.206603 #1] ERROR -- : /app/lib/autoloads/genova/code_manager/git.rb:126:in `read'
/app/lib/autoloads/genova/code_manager/git.rb:126:in `fetch_config'
/app/lib/autoloads/genova/code_manager/git.rb:53:in `load_deploy_config'
/app/lib/autoloads/genova/ecs/client.rb:21:in `initialize'
/app/lib/autoloads/genova/deploy/runner.rb:18:in `new'
/app/lib/autoloads/genova/deploy/runner.rb:18:in `run'
/app/lib/tasks/genova.thor:61:in `deploy'
/app/lib/tasks/genova.thor:92:in `service'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/runner.rb:41:in `method_missing'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:29:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:135:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/thor-1.2.2/bin/thor:6:in `<top (required)>'
/usr/local/bundle/bin/thor:25:in `load'
/usr/local/bundle/bin/thor:25:in `<main>'
I, [2024-01-06T11:34:04.212002 #1]  INFO -- : Cancel transaction.
I, [2024-01-06T11:34:04.228790 #1]  INFO -- : Deploy status updated. [failure]
```

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/pull/391
