### ISSUE TITLE
Slackデプロイ時に"uninitialized constant Genova::­Config­::ValidationError"エラーが出る場合がある

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#52]
config/deploy.ymlがないため起こる可能性がある。

```
["/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `block in load_missing_constant'", "/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'", "/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `rescue in load_missing_constant'", "/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_m...
```

**Comment by naomichi-y** [comment]
CLIデプロイでも再現する。
