### ISSUE TITLE
scheduled taskの設定が未定義の状態でデプロイするとundefined method `each'エラーが起きる

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#56]
```
E, [2019-08-12T14:04:45.021972 #1] ERROR -- : undefined method `each' for nil:NilClass
E, [2019-08-12T14:04:45.023771 #1] ERROR -- : /app/lib/genova/ecs/client.rb:97:in `deploy_scheduled_tasks'
/app/lib/genova/ecs/client.rb:72:in `deploy_scheduled_task'
/app/lib/genova/client.rb:43:in `run'
/app/lib/tasks/genova_deploy.thor:37:in `deploy'
/app/lib/tasks/genova_deploy.thor:56:in `scheduled_task'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
/usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:242:in `block in subcommand'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/app/lib/tasks/genova.thor:12:in `invoke_command'
/usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/runner.rb:44:in `method_missing'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:29:in `run'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:126:in `run'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/usr/local/bundle/gems/thor-0.19.4/bin/thor:6:in `<top (required)>'
/usr/local/bundle/bin/thor:23:in `load'
/usr/local/bundle/bin/thor:23:in `<main>'
E, [2019-08-12T14:04:45.026493 #1] ERROR -- : Interrupt was error. {"deploy id": 20190812-140415}
I, [2019-08-12T14:04:45.034169 #1]  INFO -- : Deployment has been canceled.
```

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/issues/179
