### ISSUE TITLE
Slackデプロイ時にUnable to autoload constant Github::RetrieveBranchWatchWorkerエラー

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#59]
Slackデプロイ時 (起動直後?) にエラーが起きるケースがある。
```
Unable to autoload constant Github::RetrieveBranchWatchWorker, expected /app/app/workers/github/retrieve_branch_watch_worker.rb to define it

["/usr/local/bundle/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:511:in `load_missing_constant'", "/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'", "/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'", "/usr/local/bundle/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'", "/usr...
```
エラー直後に再デプロイを行うと発生しない。

**Comment by naomichi-y** [comment]
@koda-h これ起きたことありますか?

**Comment by koda-h** [comment]
@naomichi-y いえ、これは発生したことないですね。

**Comment by koda-h** [comment]
@naomichi-y  v2.2.0 にupdateしたら発生するようになりました。

**Comment by naomichi-y** [comment]
https://github.com/metaps/genova/issues/179
