### ISSUE TITLE
ホストOSを再起動すると一部のSlackデプロイが反応しない

### ISSUE THREAD

**Issue by naomichi-y** [metaps/genova#73]
genova-sidekiq、genova-slackのステータスが `Restarting` となる。

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                    NAMES
59cc1d2e7af1        genova_sidekiq      "/usr/local/bin/dock…"   2 days ago          Restarting (1) 44 seconds ago                            genova-sidekiq
132e444b4cc9        genova_rails        "/usr/local/bin/dock…"   2 days ago          Up 5 minutes                    0.0.0.0:3000->3000/tcp   genova-rails
65062e0e288a        genova_slack        "/usr/local/bin/dock…"   2 days ago          Restarting (1) 57 seconds ago                            genova-slack
ebb5b20e865d        genova_cron         "crond -f"               2 days ago          Up 5 minutes                                             genova-cron
```

**Comment by naomichi-y** [comment]
sidekiqのログを見るとredisへの接続に失敗してる。
```
log/sidekiq.log" [readonly] 17024L, 1461852C                                                         1,1           Top
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:224:in `block in process'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:312:in `logging'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:223:in `process'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:123:in `call'
/usr/local/bundle/gems/redis-4.1.0/lib/redis.rb:1949:in `block in zrangebyscore'
/usr/local/bundle/gems/redis-4.1.0/lib/redis.rb:50:in `block in synchronize'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/redis-4.1.0/lib/redis.rb:50:in `synchronize'
/usr/local/bundle/gems/redis-4.1.0/lib/redis.rb:1948:in `zrangebyscore'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/scheduled.rb:20:in `block (2 levels) in enqueue_jobs'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/scheduled.rb:15:in `each'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/scheduled.rb:15:in `block in enqueue_jobs'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq.rb:97:in `block in redis'
/usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
/usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
/usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
/usr/local/bundle/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq.rb:94:in `redis'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/scheduled.rb:77:in `enqueue'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/scheduled.rb:68:in `block in start'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
2019-09-03T14:41:52.865Z 6 TID-gtfapr63m ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
2019-09-03T14:41:52.865Z 6 TID-gtfapr63m ERROR: undefined method `[]' for nil:NilClass
2019-09-03T14:41:52.866Z 6 TID-gtfapr63m ERROR: /app/lib/genova/sidekiq/error_handler.rb:8:in `notify'
/app/config/initializers/sidekiq.rb:3:in `block (2 levels) in <main>'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/exception_handler.rb:20:in `block in handle_exception'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/exception_handler.rb:18:in `each'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/exception_handler.rb:18:in `handle_exception'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/scheduled.rb:82:in `rescue in enqueue'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/scheduled.rb:75:in `enqueue'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/scheduled.rb:68:in `block in start'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
2019-09-03T14:41:52.867Z 6 TID-gtfapr63m ERROR: Error connecting to Redis on redis:6379 (SocketError)
2019-09-03T14:41:52.867Z 6 TID-gtfapr63m WARN: Redis::CannotConnectError: Error connecting to Redis on redis:6379 (SocketError)
2019-09-03T14:41:52.867Z 6 TID-gtfapr63m WARN: /usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:353:in `rescue in establish_connection'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:336:in `establish_connection'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:104:in `block in connect'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:299:in `with_reconnect'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:103:in `connect'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:372:in `ensure_connected'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:224:in `block in process'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:312:in `logging'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:223:in `process'
/usr/local/bundle/gems/redis-4.1.0/lib/redis/client.rb:123:in `call'
/usr/local/bundle/gems/redis-4.1.0/lib/redis.rb:2617:in `block in _scan'
/usr/local/bundle/gems/redis-4.1.0/lib/redis.rb:50:in `block in synchronize'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/redis-4.1.0/lib/redis.rb:50:in `synchronize'
/usr/local/bundle/gems/redis-4.1.0/lib/redis.rb:2616:in `_scan'
/usr/local/bundle/gems/redis-4.1.0/lib/redis.rb:2754:in `sscan'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/api.rb:11:in `block in sscan'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/api.rb:10:in `loop'
/usr/local/bundle/gems/sidekiq-5.2.5/lib/sidekiq/api.rb:10:in `sscan'
```
